// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WFAPruebaProgramacion.Models;

public partial class Opcione
{
    public int Id { get; set; }

    public string Nombre { get; set; }

    public int? Idproducto { get; set; }

    public bool? Estado { get; set; }

    public virtual Producto IdproductoNavigation { get; set; }
}