// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WFAPruebaProgramacion.Models;

public partial class Producto
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public string Nombre { get; set; }

    public int? Existencia { get; set; }

    public bool? Estado { get; set; }

    public string Proveedor { get; set; }

    public byte[] Imagen { get; set; }

    public virtual ICollection<Opcione> Opciones { get; set; } = new List<Opcione>();
}