// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WFAPruebaProgramacion.Models;

public partial class Usuario
{
    public int Id { get; set; }

    public string Usuario1 { get; set; }

    public string Clave { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Correo { get; set; }

    public string Telefono { get; set; }

    public DateOnly? Fechacreacion { get; set; }
}